import type { WordCollection } from "../collection.types";

export const autumnEquinoxCollection: WordCollection = {
  id: "autumn-equinox",
  title: "Autumn Equinox (Mabon)",
  icon: "leaf-maple",
  isWordlistViewable: true,
  startDate: new Date(2024, 8, 20), // September 20th
  endDate: new Date(2024, 8, 25), // September 25th
  words: [
    // Mabon & Harvest Balance
    "mabon",
    "equinox",
    "balance",
    "equilibrium",
    "harmony",
    "thanksgiving",
    "gratitude",
    "appreciation",
    "blessing",
    "abundance",
    "harvest",
    "reaping",
    "gathering",
    "storing",
    "preserving",
    "preparation",

    // Celtic & Pagan Traditions
    "celtic",
    "druid",
    "sacred",
    "ritual",
    "ceremony",
    "offering",
    "sacrifice",
    "tribute",
    "honor",
    "reverence",
    "worship",
    "prayer",
    "meditation",
    "reflection",
    "contemplation",
    "wisdom",

    // Harvest & Abundance
    "grain",
    "wheat",
    "barley",
    "corn",
    "apple",
    "grape",
    "wine",
    "cider",
    "bread",
    "feast",
    "bounty",
    "plenty",
    "cornucopia",
    "basket",
    "bushel",
    "store",

    // Balance & Transition
    "threshold",
    "portal",
    "gateway",
    "crossing",
    "turning",
    "pivot",
    "shift",
    "change",
    "transformation",
    "metamorphosis",
    "evolution",
    "progression",
    "cycle",
    "wheel",
    "spiral",
    "circle",

    // Autumn Colors & Nature
    "amber",
    "gold",
    "bronze",
    "copper",
    "rust",
    "crimson",
    "scarlet",
    "burgundy",
    "ochre",
    "sienna",
    "umber",
    "mahogany",
    "chestnut",
    "auburn",
    "russet",
    "tawny",

    // Earth & Elements
    "earth",
    "soil",
    "loam",
    "root",
    "seed",
    "tree",
    "oak",
    "maple",
    "birch",
    "ash",
    "elder",
    "hawthorn",
    "rowan",
    "willow",
    "pine",
    "cedar",

    // Wisdom & Maturity
    "wisdom",
    "knowledge",
    "understanding",
    "insight",
    "clarity",
    "truth",
    "maturity",
    "experience",
    "learning",
    "teaching",
    "guidance",
    "counsel",
    "advice",
    "elder",
    "ancestor",
    "heritage",
  ],
};
