import type { WordCollection } from "../collection.types";
import { createCollection } from "../logic";

const bloomWordList = [
  "bloom",
  "blossom",
  "flower",
  "petal",
  "stamen",
  "pistil",
  "nectar",
  "pollen",
  "fragrant",
  "scent",
  "aroma",
  "perfume",
  "sweet",
  "honey",
  "sugar",
  "syrup",
  "buzz",
  "hum",
  "drone",
  "wing",
  "flutter",
  "dance",
  "circle",
  "visit",
  "gather",
  "collect",
  "harvest",
  "pollinate",
  "fertilize",
  "cross",
  "hybrid",
  "variety",
  "species",
  "diverse",
  "vibrant",
  "bright",
  "vivid",
  "bold",
  "rich",
  "deep",
  "intense",
  "brilliant",
  "radiant",
  "glowing",
  "luminous",
  "golden",
  "yellow",
  "orange",
  "red",
  "pink",
  "purple",
  "blue",
  "white",
  "cream",
  "ivory",
  "abundant",
  "plentiful",
  "overflow",
  "burst",
  "explode",
  "cascade",
  "shower",
  "rain",
  "fall",
  "drift"
];

export const bloomCollection: WordCollection = createCollection(
  "bloom",
  "Bloom & Buzz",
  bloomWordList,
  {
    icon: "flower",
    isWordlistViewable: true,
    startDate: new Date(new Date().getFullYear(), 3, 20), // April 20th
    endDate: new Date(new Date().getFullYear(), 4, 31), // May 31st
  },
); 