import type { WordCollection } from "../collection.types";
import { createCollection } from "../logic";

// Removed deduplicateArray and local createCollection helper

const colorsWordList = [
  "red",
  "blue",
  "green",
  "yellow",
  "orange",
  "purple",
  "pink",
  "violet",
  "brown",
  "black",
  "white",
  "gray",
  "silver",
  "gold",
  "bronze",
  "azure",
  "sapphire",
  "pearl",
  "navy",
  "tan",
  "cream",
  "lavender",
  "lilac",
  "mint",
  "olive",
  "shadow",
  "highlight",
  "spectrum",
  "shade",
  "tint",
  "vibrant",
  "glow",
  "gleam",
  "sparkle",
  "flash",
  "beam",
  "ray",
  "radiant",
  "bright",
  "dim",
  "fade",
  "dark",
  "light",
  "dazzle",
  "flicker",
  "illuminate",
  "absorb",
  "transparent",
  "opaque",
  "translucent",
  "burn",
  "brass",
  "rose",
  "slate",
]; // Removed deduplicateArray wrapper

export const colorsCollection: WordCollection = createCollection(
  "colors",
  "Colors & Light",
  colorsWordList,
  { icon: "palette", isWordlistViewable: true },
);
