import type { WordCollection } from "../collection.types";
import { createCollection } from "../logic";

const fantasyWordList = [
  "spell",
  "veil",
  "magic",
  "enchant",
  "charm",
  "sorcerer",
  "oracle",
  "mystic",
  "familiar",
  "curse",
  "realm",
  "domain",
  "kingdom",
  "castle",
  "keep",
  "hollow",
  "path",
  "trail",
  "journey",
  "hero",
  "champion",
  "guide",
  "elder",
  "artifact",
  "treasure",
  "gold",
  "silver",
  "gem",
  "jewel",
  "crown",
  "staff",
  "rod",
  "shield",
  "sword",
  "blade",
  "bow",
  "arrow",
  "mount",
  "beast",
  "shadow",
  "light",
  "dawn",
  "midnight",
  "moon",
  "star",
  "sun",
  "cosmic",
  "celestial",
  "dream",
  "prophecy",
  "myth",
  "tale",
  "epic",
  "song",
  "puzzle",
  "secret",
  "mystery",
  "whisper",
  "echo",
];

export const fantasyCollection: WordCollection = createCollection(
  "fantasy",
  "Fantasy & Mysticism",
  fantasyWordList,
  { icon: "script-text-outline", isWordlistViewable: true }, // Example icon, adjust as needed
);
