import type { WordCollection } from "../collection.types";
import { createCollection } from "../logic";

const greeningWordList = [
  "sprout",
  "emerge",
  "bud",
  "shoot",
  "tender",
  "green",
  "verdant",
  "lush",
  "flourish",
  "thrive",
  "grow",
  "expand",
  "unfold",
  "awaken",
  "stir",
  "stretch",
  "reach",
  "climb",
  "rise",
  "ascend",
  "soil",
  "earth",
  "ground",
  "loam",
  "fertile",
  "rich",
  "nourish",
  "feed",
  "sustain",
  "rain",
  "shower",
  "drizzle",
  "mist",
  "dew",
  "moisture",
  "drink",
  "soak",
  "absorb",
  "saturate",
  "fresh",
  "clean",
  "pure",
  "clear",
  "hope",
  "promise",
  "potential",
  "possible",
  "new",
  "young",
  "infant",
  "birth",
  "born",
  "create",
  "form",
  "shape",
  "mold",
  "craft",
  "build",
  "construct",
  "establish",
  "found",
  "root",
  "anchor",
  "ground",
  "steady",
  "stable",
  "firm",
];

export const greeningCollection: WordCollection = createCollection(
  "greening",
  "Greening Earth",
  greeningWordList,
  {
    icon: "sprout",
    isWordlistViewable: true,
    startDate: new Date(new Date().getFullYear(), 2, 1), // March 1st
    endDate: new Date(new Date().getFullYear(), 3, 30), // April 30th
  },
);
