import type { WordCollection } from "../collection.types";
import { createCollection } from "../logic";

const renewalWordList = [
  "fresh",
  "begin",
  "start",
  "dawn",
  "clear",
  "crisp",
  "pure",
  "bright",
  "resolve",
  "intent",
  "focus",
  "goal",
  "path",
  "journey",
  "step",
  "forward",
  "progress",
  "growth",
  "change",
  "transform",
  "renew",
  "refresh",
  "cleanse",
  "clarity",
  "vision",
  "purpose",
  "dream",
  "hope",
  "aspire",
  "breathe",
  "reflect",
  "ponder",
  "contemplate",
  "quiet",
  "still",
  "peace",
  "calm",
  "center",
  "balance",
  "mindful",
  "aware",
  "present",
  "moment",
  "open",
  "ready",
  "prepare",
  "plan",
  "organize",
  "simplify",
  "essential",
  "core",
  "foundation",
  "root",
  "ground",
  "steady",
  "strong",
  "resilient",
  "capable",
  "possible",
  "potential",
  "energy",
  "vital",
  "alive",
];

export const renewalCollection: WordCollection = createCollection(
  "renewal",
  "Renewal & Reflection",
  renewalWordList,
  {
    icon: "sunrise",
    isWordlistViewable: true,
    startDate: new Date(new Date().getFullYear(), 0, 1), // January 1st
    endDate: new Date(new Date().getFullYear(), 0, 20), // January 20th
  },
);
