import type { WordCollection } from "../collection.types";
import { createCollection } from "../logic";

const seasonsWordList = [
  "spring",
  "summer",
  "autumn",
  "fall",
  "winter",
  "snow",
  "thunder",
  "frost",
  "blossom",
  "rain",
  "storm",
  "cloud",
  "breeze",
  "wind",
  "hurricane",
  "tornado",
  "hail",
  "sleet",
  "fog",
  "mist",
  "rainbow",
  "humid",
  "dry",
  "wet",
  "cold",
  "hot",
  "warm",
  "cool",
  "freeze",
  "thaw",
  "drought",
  "flood",
  "shower",
  "drizzle",
  "temperature",
  "climate",
  "seasonal",
  "solstice",
  "bloom",
  "harvest",
  "sunlight",
  "shadow",
  "sunset",
  "twilight",
  "night",
  "forecast",
  "weather",
  "sky",
  "lightning",
];

export const seasonsCollection: WordCollection = createCollection(
  "seasons",
  "Seasons & Weather",
  seasonsWordList,
  { icon: "weather-partly-cloudy", isWordlistViewable: true }, // Example icon
);
