import type { WordCollection } from "../collection.types";

export const springEquinoxCollection: WordCollection = {
  id: "spring-equinox",
  title: "Spring Equinox (Ostara)",
  icon: "weather-sunny",
  isWordlistViewable: true,
  startDate: new Date(2024, 2, 18), // March 18th
  endDate: new Date(2024, 2, 23), // March 23rd
  words: [
    // Ostara & Spring Awakening
    "ostara",
    "equinox",
    "balance",
    "equilibrium",
    "awakening",
    "rebirth",
    "renewal",
    "resurrection",
    "emergence",
    "sprouting",
    "budding",
    "unfurling",
    "quickening",
    "stirring",
    "rising",
    "ascending",

    // Pagan & Earth-Based Spirituality
    "goddess",
    "maiden",
    "earth",
    "gaia",
    "mother",
    "fertility",
    "abundance",
    "blessing",
    "ritual",
    "ceremony",
    "sacred",
    "holy",
    "divine",
    "spirit",
    "energy",
    "power",

    // Light & Dark Balance
    "light",
    "darkness",
    "shadow",
    "dawn",
    "dusk",
    "threshold",
    "portal",
    "gateway",
    "crossing",
    "transition",
    "turning",
    "pivot",
    "fulcrum",
    "center",
    "harmony",
    "unity",

    // Spring Symbols & Nature
    "egg",
    "seed",
    "nest",
    "hare",
    "rabbit",
    "lamb",
    "chick",
    "butterfly",
    "flower",
    "blossom",
    "bloom",
    "petal",
    "nectar",
    "pollen",
    "honey",
    "sweet",

    // Elements & Natural Forces
    "air",
    "wind",
    "breeze",
    "breath",
    "whisper",
    "earth",
    "soil",
    "loam",
    "root",
    "water",
    "rain",
    "stream",
    "fire",
    "spark",
    "flame",
    "warmth",

    // Colors of Spring
    "green",
    "yellow",
    "pink",
    "white",
    "purple",
    "lavender",
    "violet",
    "gold",
    "silver",
    "emerald",
    "jade",
    "mint",
    "sage",
    "lime",
    "chartreuse",
    "pastel",
  ],
};
