import type { WordCollection } from "../collection.types";

export const summerSolsticeCollection: WordCollection = {
  id: "summer-solstice",
  title: "Summer Solstice (Litha)",
  icon: "white-balance-sunny",
  isWordlistViewable: true,
  startDate: new Date(2024, 5, 18), // June 18th
  endDate: new Date(2024, 5, 23), // June 23rd
  words: [
    // Litha & Midsummer
    "litha",
    "midsummer",
    "solstice",
    "peak",
    "zenith",
    "apex",
    "pinnacle",
    "climax",
    "maximum",
    "fullness",
    "abundance",
    "prosperity",
    "wealth",
    "richness",
    "bounty",
    "plenty",

    // Sun God & Solar Power
    "sun",
    "solar",
    "radiant",
    "blazing",
    "brilliant",
    "luminous",
    "golden",
    "amber",
    "fire",
    "flame",
    "blaze",
    "inferno",
    "heat",
    "warmth",
    "energy",
    "power",

    // Pagan & Celtic Traditions
    "druid",
    "celtic",
    "oak",
    "sacred",
    "grove",
    "circle",
    "stone",
    "altar",
    "ritual",
    "ceremony",
    "blessing",
    "invocation",
    "prayer",
    "chant",
    "song",
    "dance",

    // Midsummer Magic & Faeries
    "magic",
    "enchantment",
    "spell",
    "charm",
    "faerie",
    "fairy",
    "fae",
    "sprite",
    "pixie",
    "elf",
    "woodland",
    "forest",
    "glade",
    "meadow",
    "wildflower",
    "herb",

    // Herbs & Plants of Power
    "lavender",
    "rosemary",
    "sage",
    "thyme",
    "basil",
    "mint",
    "chamomile",
    "vervain",
    "mugwort",
    "yarrow",
    "elderflower",
    "honeysuckle",
    "jasmine",
    "rose",
    "lily",
    "iris",

    // Fire & Light Celebrations
    "bonfire",
    "torch",
    "candle",
    "lantern",
    "beacon",
    "spark",
    "ember",
    "glow",
    "flicker",
    "illuminate",
    "brighten",
    "kindle",
    "ignite",
    "burn",
    "consume",
    "transform",

    // Nature's Peak Power
    "flourishing",
    "thriving",
    "blooming",
    "ripening",
    "maturing",
    "growing",
    "expanding",
    "bursting",
    "overflowing",
    "cascading",
    "vibrant",
    "alive",
    "vital",
    "strong",
    "mighty",
    "potent",
  ],
};
