import type { WordCollection } from "../collection.types";

export const winterSolsticeCollection: WordCollection = {
  id: "winter-solstice",
  title: "Winter Solstice (Yule)",
  icon: "weather-night",
  isWordlistViewable: true,
  startDate: new Date(2024, 11, 18), // December 18th
  endDate: new Date(2024, 11, 23), // December 23rd
  words: [
    // Yule & Winter Solstice
    "yule",
    "solstice",
    "rebirth",
    "renewal",
    "return",
    "awakening",
    "resurrection",
    "revival",
    "restoration",
    "regeneration",
    "reemergence",
    "comeback",
    "recovery",
    "healing",
    "hope",
    "promise",

    // Light in Darkness
    "light",
    "candle",
    "flame",
    "fire",
    "spark",
    "ember",
    "glow",
    "radiance",
    "luminance",
    "brightness",
    "illumination",
    "beacon",
    "torch",
    "lantern",
    "star",
    "constellation",

    // Pagan & Norse Traditions
    "norse",
    "celtic",
    "druid",
    "pagan",
    "heathen",
    "ritual",
    "ceremony",
    "sacred",
    "holy",
    "divine",
    "spiritual",
    "mystical",
    "magical",
    "enchanted",
    "blessed",
    "hallowed",

    // Yule Log & Fire Traditions
    "log",
    "oak",
    "ash",
    "pine",
    "cedar",
    "juniper",
    "holly",
    "ivy",
    "mistletoe",
    "evergreen",
    "wreath",
    "garland",
    "bough",
    "branch",
    "needle",
    "cone",

    // Winter & Cold
    "winter",
    "frost",
    "ice",
    "snow",
    "crystal",
    "frozen",
    "cold",
    "chill",
    "bitter",
    "harsh",
    "stark",
    "barren",
    "dormant",
    "sleeping",
    "resting",
    "quiet",

    // Longest Night & Darkness
    "darkness",
    "night",
    "shadow",
    "depth",
    "void",
    "abyss",
    "mystery",
    "unknown",
    "hidden",
    "secret",
    "veiled",
    "shrouded",
    "cloaked",
    "masked",
    "concealed",
    "obscured",

    // Rebirth & New Beginnings
    "birth",
    "beginning",
    "start",
    "origin",
    "genesis",
    "inception",
    "initiation",
    "commencement",
    "dawn",
    "sunrise",
    "emergence",
    "sprouting",
    "budding",
    "growing",
    "developing",
    "evolving",

    // Celebration & Community
    "feast",
    "gathering",
    "family",
    "kinship",
    "community",
    "togetherness",
    "unity",
    "bond",
    "connection",
    "love",
    "warmth",
    "comfort",
    "shelter",
    "protection",
    "safety",
    "security",
  ],
};
